# Generated by Django 4.2.1 on 2023-05-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="transaction",
            fields=[
                (
                    "tr_id",
                    models.CharField(max_length=120, primary_key=True, serialize=False),
                ),
                ("NIK", models.CharField(max_length=120)),
                ("total", models.BigIntegerField()),
                ("start_date", models.DateTimeField()),
                (
                    "jenis_transaction",
                    models.CharField(
                        choices=[("C", "Cash"), ("R", "Credit"), ("W", "E-Wallet")],
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "NIK",
                    models.CharField(max_length=120, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=120)),
                ("email", models.CharField(max_length=120)),
                ("password", models.CharField(max_length=100)),
                ("alamat", models.TextField()),
                ("phone_num", models.CharField(max_length=14)),
                ("room", models.CharField(max_length=4)),
                ("is_verified", models.BooleanField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
            ],
        ),
    ]
